name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Go setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Check Go Build/lint/tests
      run: |
        sudo apt-get update -qq && \
        sudo apt-get install -y -qq libzmq3-dev&&  \
        go get -u golang.org/x/lint/golint
        golint ./...
        make build
        source .env
        go test
        
    - name: Install python
      run: |
        sudo apt-get install -y -qq python3 python3-dev
        sudo apt-get install gcc libpq-dev -y
        sudo apt-get install python-dev  python-pip -y
        sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
        pip3 install wheel

    - name: Install requirements
      run: |
        pip3 install -r ./consumer/requirements.txt

    - name: linting python
      run: |
        pip3 install flake8
        python3 -m flake8 ./consumer

    - name:  python tests
      run: |
        python3 ./consumer/test.py
